spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
server:
  servlet:
    context-path: winter

mybatis:
  type-aliases-package: com.example.winter.entity
  mapper-locations: classpath:mapper/*.xml

