spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
server:
  servlet:
    context-path: winter

mybatis:
  #config-location: classpath:mapper/*.xml
  type-aliases-package: com.example.winter.entity
  # mapper-locations: classpath:com/example/winter/dao/mybatis/*.xml
  mapper-locations: classpath:mapper/*.xml

